


// ALOOOOG

// GET THE CHALLENGE

export const  GET_THE_CHALLENGE_LOADING="GET_THE_CHALLENGE_LOADING"
export const  GET_THE_CHALLENGE_SUCCESS="GET_THE_CHALLENGE_SUCCESS"
export const  GET_THE_CHALLENGE_ERROR="GET_THE_CHALLENGE_ERROR"

// UPDATE THE TIMER

export const SOCKET_UPDATE_TIMER="SOCKET_UPDATE_TIMER"

// UPDATE THE LEADERBOARD

export const SOCKET_UPDATE_LEADERBOARD="SOCKET_UPDATE_TIMER"
